name: tech_world_networking_types
description: Types for objects sent over the network.
version: 0.0.0-1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
